language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-23

before_install:
   - rvm install 2.3.1
   #- gem install fastlane
   - gem install screengrab -v 0.3.2
   - gem install supply -v 0.5.2
   - gem install fastlane_core -v 0.38.0
   - echo y | gem uninstall fastlane_core -v $(gem list | grep '^fastlane_co' | cut -d\( -f2- | cut -d\) -f1)

before_script:
  - supply init
  - android list device
  - ./gradlew assembleDebug assembleAndroidTest
  # Create and start Phone emulator
  - echo no | android create avd --force -n testphone -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd testphone -no-skin -no-audio -no-window &
  - source scripts/environmentSetup.sh && waitForAVD
  #- adb wait-for-device
  - adb shell input keyevent 82
  - screengrab
  - adb -s emulator-5554 emu kill
  # Create and start 7" tablet emulator
  - echo no | android create avd --force -n testtablet7 -t $ANDROID_TARGET --abi $ANDROID_ABI -d 28
  - emulator -avd testtablet7 -no-skin -no-audio -no-window &
  - source scripts/environmentSetup.sh && waitForAVD
  - adb shell input keyevent 82
  - screengrab -d "sevenInch"
  - adb -s emulator-5554 emu kill
  # Create and start 10" tablet emulator
  - echo no | android create avd --force -n testtablet10 -t $ANDROID_TARGET --abi $ANDROID_ABI -d 29
  - emulator -avd testtablet10 -no-skin -no-audio -no-window &
  - source scripts/environmentSetup.sh && waitForAVD
  - adb shell input keyevent 82
  - screengrab -d "tenInch"
script:
  - ./gradlew assembleRelease
  - supply -j "keys.json" -p "com.eurisko.testappgithub" -a "production" -m "fastlane/metadata/android" -b "app/build/outputs/apk/app-release.apk"
