language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-23

before_install:
   - rvm install 2.3.1
   - gem install screengrab
   - gem install supply
   #- gem install fastlane_core -v 0.38.0
   #- gem uninstall fastlane_core -v 0.39.0

before_script:
  - ls
  - pwd
  - supply init
  - ./gradlew assembleDebug assembleAndroidTest
  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - source scripts/environmentSetup.sh && waitForAVD
  #- adb wait-for-device
  - adb shell input keyevent 82
  - screengrab

script:
  - ./gradlew assembleRelease
  - supply -j "keys.json" -p "com.eurisko.testappgithub" -a "production" -m "fastlane/metadata/android" -b "app/build/outputs/apk/app-release.apk"
