language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-23

before_install:
   - rvm install 2.1.5
   - gem install fastlane -v 1.84.0

before_script:
  #- supply init
  - ./gradlew assembleDebug assembleAndroidTest
  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &
  - adb devices -l ; echo "result code: $?"
  - screengrab

script:
  - ./gradlew assembleRelease
  - supply -j "keys.json" -p "com.eurisko.testappgithub" -a "production" -m "fastlane/metadata/android" -b $CIRCLE_ARTIFACTS/outputs/apk/app-release.apk
