# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.83.0"

lane :deploy do 
  #Generate key files 
  #dir = “./fastlane/certs” 
  #add_key( 
    #keystore_path: File.join(dir, “release.keystore”),
    #play_p12_path: File.join(dir, “play.p12”)
  #)
  #Build 
  gradle(task: "assembleRelease")
  
  #Screenshots
  screengrab(
    locales: ['en-US'],
    clear_previous_screenshots: true,
    app_apk_path: :GRADLE_APK_OUTPUT_PATH
  )
  
  #Upload to Google Play 
  supply( track: "production" ) 
  #Delete key files
  #remove_key 
end

#module Fastlane
  #module Actions
    #class AddKeyAction < Action
      #def self.run(params)
        #keystore_path = params[:keystore_path]
        #play_p12_path = params[:play_p12_path]
        #encryption_secret = ENV["ENCRYPTION_SECRET"]
        #sh "openssl aes-256-cbc -k #{encryption_secret} -in #{keystore_path}.enc -d -a -out #{keystore_path}"
        #sh "openssl aes-256-cbc -k #{encryption_secret} -in #{play_p12_path}.enc -d -a -out #{play_p12_path}"
      #end
    #end
  #end 
#end 

#module Fastlane
  #module Actions
    #class RemoveKeyAction < Action
      #def self.run(params) 
        #sh "rm -rf fastlane/certs" 
      #end
    #end
  #end
#end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
